### ISSUE TITLE
好像有问题额

### ISSUE THREAD

**Issue by shihuojian** [xialeistudio/wxbizmsgcrypt-nodejs#1]
好像有问题额

**Comment by xialeistudio** [comment]
报错的话把错误贴出来

**Comment by kknono** [comment]
Error: Cannot find module 'babel-runtime/helpers/classCallCheck'

**Comment by xialeistudio** [comment]
```
npm install babel-runtime
```

**Comment by kknono** [comment]
var WxBizMsgCrypt = require('wxbizmsgcrypt').WxBizMsgCrypt;
var wxbizmsgcrypt = new WxBizMsgCrypt('xxx','xxx','xxxx');

TypeError: WxBizMsgCrypt is not a constructor
...请问下安装后，实例化报错

**Comment by xialeistudio** [comment]
有用es6吗？

**Comment by kknono** [comment]
用的啊

**Comment by kknono** [comment]
Node.js v6.14.1
目前使用var WxBizMsgCrypt = require('wxbizmsgcrypt').WxBizMsgCrypt.default;  可以成功

**Comment by xialeistudio** [comment]
那你需要安装`babel-plugin-transform-es2015-modules-commonjs`去掉显式写default
