### ISSUE TITLE
完全无法使用

### ISSUE THREAD

**Issue by illusory-love** [xialeistudio/wxbizmsgcrypt-nodejs#3]
`import {WxBizMsgCrypt} from 'wxbizmsgcrypt';
const wxbizmsgcrypt = new WxBizMsgCrypt(token,encodingAesKey,appId);`

直接报错: TypeError: _wxbizmsgcrypt.WxBizMsgCrypt is not a constructor

改成下面后 new 正常
`const wxbizmsgcrypt = new WxBizMsgCrypt.default(token,encodingAesKey,appId);`

随之如下使用时又报错
`wxbizmsgcrypt.decryptMsg('msg_signature','时间戳','随机字符串','加密的XML').then(function(xml) {
  console.log(xml);
});`

跟踪执行到 `_XMLParser2.default.extrace(postData)` 时报错

继续排查 postData 并不是一个 xml 串, 而是未解密的加密数组对象

`postData = [ 'G83D5fJ8erWkIXLF2FEiHkavKQAk3CCh51wiauCJOLxbOVb16Cyo5DUhHHTO4cGZo7kZkxc3shtiPzyckLBtxvaqIwN0s4JtCnUr2xVrUimv0DJyOMSNjTSEoUe46iz3I8gByvowgIaFgpW5Wa38j10OEefUw4uf/qfUYTvJnNSkVp1zRe1SbaVHv1NGP2TPor1RdZ4qFDxC91rf52w9f9HnVX2JvDrQWJ88sggYSNiCIn3lxPxspYzqjjohtsBuSCA/f7qdJVTI7qxFAVaD/tLZjiuyb1WenTig09NqOue4fGhtPumKhTBA+fiCruBTHenE8f9cal/p9Vg5XGGKn+60mPJs1vhhY43GQXXB5tVwbTs9saKcg885kHEpkTeZ0f4ZJvXjqtpTufxrhqdmXWcmJyzxHcekbe1Z4Ki+ij/NIMSjIRu85JctfoG/dTJ254qGECDzQ==' ]`

**Comment by illusory-love** [comment]
排除了我项目插件的问题, 作了一个最简单的测试

在一个空文件夹中新键文件 test.js 

内容仅有:

var WxBizMsgCrypt = require('wxbizmsgcrypt').WxBizMsgCrypt;
var wxbizmsgcrypt = new WxBizMsgCrypt(token,encodingAesKey,appId)

直接执行文件:  $ node ./test.js

情况如上所述

加入了插件: `babel-plugin-transform-es2015-modules-commonjs`

**Comment by xialeistudio** [comment]
收到，有空看看。
估计是module default引起的问题

**Comment by xialeistudio** [comment]
> 继续排查 postData 并不是一个 xml 串, 而是未解密的加密数组对象
1. 这个是你传输过来的数据格式有问题，估计你使用了koa-xml-body之类的中间件
> 排除了我项目插件的问题, 作了一个最简单的测试
1. 请熟悉babel使用之后再做测试，我项目的单元测试是通过的。
